server:
  port: 443
  ssl:
    key-store: classpath:ssl.buymaa.site.jks
    key-store-password: 08072re075
    key-store-type: PKCS12
    key-alias: ssl.buymaa.site
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:mysql://rm-cn-to34lj8kh0002gjo.rwlb.rds.aliyuncs.com:3306/milk-private
    username: dms_user_92ba109
    password: aliyun-008
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  configuration:
    map-underscore-to-camel-case: true